# db:
#   image: mysql
#   expose:
#     - "3306"
#   volumes:
#     - ./db:/var/lib/mysql
#   environment:
#     - MYSQL_DATABASE=achievements
#     - MYSQL_ROOT_PASSWORD=root

web:
  build: .
  command: python ./my_django/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8081:8000"
  # links:
  #   - db
